config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :articles, only: [:index]
  get '/quiz', to: 'articles#quiz'
  post '/quiz_submit', to: 'articles#quiz_submit'
  match 'reset_counts', to: 'articles#reset_counts', via: [:get, :post], as: :reset_counts



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/bangladesh_article.rb
# frozen_string_literal: true

class BangladeshArticle < Article
end

app/models/bird_article.rb
# frozen_string_literal: true

class BirdArticle < Article
  has_one_attached :mp3_file
end

app/models/geography_article.rb
# frozen_string_literal: true

class GeographyArticle < Article
end

app/models/history_article.rb
# frozen_string_literal: true

class HistoryArticle < Article
end

app/models/music_article.rb
class MusicArticle < Article
end

app/models/nba_article.rb
# frozen_string_literal: true

class NbaArticle < Article
end

app/models/technology_article.rb
# frozen_string_literal: true

class TechnologyArticle < Article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def quiz
    # Initialize the counts from the session
    @correct_count = session[:correct_count] || 0
    @incorrect_count = session[:incorrect_count] || 0

    # Determine the category
    if params[:category]
      # Set the category from params and store it in the session
      category_type = params[:category]
      session[:quiz_category] = category_type
    elsif session[:quiz_category]
      # Get the category from the session if not provided in params
      category_type = session[:quiz_category]
    else
      # Default category if none is set
      category_type = 'MusicArticle'
      session[:quiz_category] = category_type
    end

    # Ensure the category is one of the allowed types
    allowed_category_types = %w[MusicArticle BangladeshArticle BirdArticle NbaArticle]
    category_type = 'MusicArticle' unless allowed_category_types.include?(category_type)

    @category_type = category_type

    # Fetch a random article from the selected category
    @article = category_type.constantize.order('RANDOM()').first
    @correct_title = @article.title


    @bird_sound = @article.mp3_file if @article.is_a?(BirdArticle)
    if @category_type == 'NbaArticle'
      @nba_article = NbaArticle.order('RANDOM()').first
      @image_path = @nba_article.image_path.sub(/\Apublic\//, '/') if @nba_article&.image_path.present?
    end


    @possible_titles = category_type.constantize
                                    .where.not(id: @article.id)
                                    .order('RANDOM()')
                                    .limit(3)
                                    .pluck(:title)
    @possible_titles << @correct_title
    @possible_titles.shuffle!



  end

  def quiz_submit
    selected_title = params[:selected_title]
    correct_title = params[:correct_title]

    puts "Comparing: #{selected_title}, and #{correct_title}"
    if selected_title == correct_title
      flash[:notice] = 'Correct!'
      session[:correct_count] = (session[:correct_count] || 0) + 1
    else
      flash[:alert] = "Incorrect, the title was #{correct_title}"
      session[:incorrect_count] = (session[:incorrect_count] || 0) + 1
    end


    puts "The correct count: #{@correct_count}"

    # Redirect to the quiz and display flash messages
    redirect_to quiz_path
  end
  def reset_counts
    # Reset the correct_count and incorrect_count to 0
    session[:correct_count] = 0
    session[:incorrect_count] = 0

    # Redirect back to the quiz page
    redirect_to quiz_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="container text-center mt-5">
  <h1 class="mb-4">Welcome to the World's Best Trivia Game!</h1>
  <div class="p-3 bg-light rounded">
  <h4>Here are the rules for the quiz:</h4>
  <ol class="list-group list-group-flush text-start list-group-numbered ">
    <li class="list-group-item">Select a category to start the quiz.</li>
    <li class="list-group-item">You will be presented with a question and multiple choices.</li>
    <li class="list-group-item">Select the correct answer to score points.</li>
  </ol>
</div>
</div>

<!-- Quiz Category Selection -->
<div class="container text-center mt-5 p-3 bg-light rounded">
  <h2>Select a Quiz Category</h2>
  <ul class="list-unstyled d-flex justify-content-center">
    <li class="mx-2"><%= link_to 'Music', quiz_path(category: 'MusicArticle'), class: 'btn btn-primary' %></li>
    <li class="mx-2"><%= link_to 'Bangladesh', quiz_path(category: 'BangladeshArticle'), class: 'btn btn-primary' %></li>
    <li class="mx-2"><%= link_to 'Bird Songs', quiz_path(category: 'BirdArticle'), class: 'btn btn-primary' %></li>
    <li class="mx-2"><%= link_to 'NBA Players', quiz_path(category: 'NbaArticle'), class: 'btn btn-primary' %></li>
  </ul>
</div>

app/views/articles/quiz.html.erb
<div class="container mt-4">
  <div class="row ">
    <div>
      <%= link_to 'Change Category', '/articles', class: 'btn btn-primary' %>

      <h1 class="mb-3 text-center"><%= @category_type %> Quiz</h1>
    </div>
  </div>


  <!-- Display Bird Sound if available -->
  <% if @bird_sound %>
    <div class="mb-3">
      <p>Listen to the bird sound and guess the bird:</p>
      <audio controls class="w-100">
        <source src="<%= url_for(@bird_sound) %>" type="audio/mpeg">
        Your browser does not support the audio element.
      </audio>
    </div>
  <% else %>
    <p class="bg-light rounded p-3"><%= @article.description %></p>
  <% end %>


  <% if @nba_article && @image_path %>
    <h2>Who is this NBA player?</h2>
    <div class="text-center mb-4">

      <%= image_tag(@image_path.sub('public/', '/'), alt: @nba_article.title, class: "img-fluid", style: "max-width: 250px;") %>
    </div>
  <% end %>
  <div class="row align-items-center justify-content-center mb-3 bg-info bg-opacity-25 rounded p-3">
    <div class="col text-center">
      <p class="text-success mb-0">Correct Answers: <%= @correct_count %></p>
    </div>
    <div class="col text-center">
      <p class="text-danger mb-0">Incorrect Answers: <%= @incorrect_count %></p>
    </div>
    <div class="col text-center">
      <%= link_to 'Reset Counts', reset_counts_path, method: :post, class: 'btn btn-danger' %>
    </div>
  </div>

  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-warning"><%= flash[:alert] %></div>
  <% end %>

  <%= form_tag quiz_submit_path, method: :post, class: 'mb-3' do %>
    <div class="list-group">
      <% @possible_titles.each do |title| %>
        <label class="list-group-item">
          <%= radio_button_tag 'selected_title', title, false, id: "title_#{title}", class: 'me-2' %>
          <%= title %>
        </label>
      <% end %>
    </div>
    <%= hidden_field_tag 'correct_title', @correct_title %>
    <%= submit_tag 'Submit', class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </body>
</html>